# Generated by Django 4.2 on 2024-05-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_estudiantecurso_estudiante_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default='NombreDefault', max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
