# Generated by Django 4.2 on 2024-05-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_estudiante_nombre_alter_profesor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
